language: nodejs

nodejs:
  - "10.16.1"

before_script: 
  - cd vue-resume
  - npm install
  
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 6fd7511744603e183d5a19f408cf090b9ee820bb  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master